In [ ]:
# Specific Column

In [1]:
import numpy as np

In [2]:
numbers=np.arange(1,61)
num=numbers.reshape(10,6)
num

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [3]:
num[:,2]

array([ 3,  9, 15, 21, 27, 33, 39, 45, 51, 57])

In [4]:
# specific row
num[3,:]

array([19, 20, 21, 22, 23, 24])

In [5]:
products=np.array(['Mobile','TV','Bottle','Desktop'])
products

array(['Mobile', 'TV', 'Bottle', 'Desktop'], dtype='<U7')

In [ ]:
# here u7 -> unicode and 7 is the maximum char in a word

In [6]:
name=np.array(['Ram','Bob'])
name

array(['Ram', 'Bob'], dtype='<U3')