# Numeric Python

In [1]:
import numpy as np

In [2]:
a=[2,4,6]
b=[1,3,5]
a

[2, 4, 6]

In [5]:
a_array=np.array(a)
print(type(a_array))
print(a_array)

<class 'numpy.ndarray'>
[2 4 6]


In [6]:
b_array=np.array(b)
print(b_array)

[1 3 5]


In [8]:
addition_list=a+b
addition_numpy=a_array+b_array
print(addition_list)
print(addition_numpy)

[2, 4, 6, 1, 3, 5]
[ 3  7 11]


In [10]:
divide_float=a_array/b_array
divide_int = a_array // b_array
print(divide_float)
print(divide_int)

[2.         1.33333333 1.2       ]
[2 1 1]


In [19]:
# multi-Dim array
# all the list should have same shape
multi_d=np.array([
    [2,4,6],
    [1,3,5],
    [5,6,7]
])
print(multi_d)
print(multi_d.shape)

[[2 4 6]
 [1 3 5]
 [5 6 7]]
(3, 3)
