# Slicing

In [1]:
import numpy as np

### 1D array

In [2]:
num_1d=np.arange(1,11)
num_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
num_1d[2:4]

array([3, 4])

### 2D array

In [4]:
num=np.arange(1,51)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [5]:
num_2d=num.reshape(10,5)
num_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [9]:
# without using numpy
for row in num_2d[1:3]:
    print(row[1:3])

[7 8]
[12 13]


In [10]:
# we can do directly by: num_2d[row,column]
num_2d[1:3,1:3]

array([[ 7,  8],
       [12, 13]])