# Zeros and Ones

In [2]:
import numpy as np

In [ ]:
# zero=np.array(shape,dtype=int/float)

In [3]:
zero_1d=np.zeros(6,dtype=int)
zero_1d

array([0, 0, 0, 0, 0, 0])

In [4]:
one_1d=np.ones(6,dtype=int)
one_1d

array([1, 1, 1, 1, 1, 1])

In [5]:
one_2d=np.ones((5,6),dtype=int)
one_2d

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [6]:
one_2d=np.zeros((5,6),dtype=int)
one_2d

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])